# Generated by Django 5.1.1 on 2024-09-19 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categoria_post_contenido_post_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fch_creado',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 1, 12, 27, 321249, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 1, 12, 27, 320252, tzinfo=datetime.timezone.utc)),
        ),
    ]
