# Generated by Django 5.1.1 on 2024-10-08 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comentario_fch_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fch_creado',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 22, 7, 2, 485946, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 22, 7, 2, 484763, tzinfo=datetime.timezone.utc)),
        ),
    ]
